import { CityDefinition } from './types'
import { INDORE_LOCALITIES } from './indore-localities'

export const CITY_REGISTRY: CityDefinition[] = [
  {
    slug: 'indore',
    name: 'Indore',
    state: 'Madhya Pradesh',
    country: 'IN',
    status: 'live',
    tagline: 'Verified rental reels from Instagram & YouTube',
    accent: '#3b82f6',
    accentMuted: '#1d4ed8',
    center: { lat: 22.7196, lng: 75.8577 },
    featuredLocalitySlugs: ['vijay_nagar', 'scheme_54', 'nipania', 'palasia', 'bhawarkua', 'super_corridor'],
    localities: INDORE_LOCALITIES,
  },
  {
    slug: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    country: 'IN',
    status: 'coming_soon',
    tagline: 'Bandra to Navi Mumbai — reels turned searchable',
    accent: '#f59e0b',
    accentMuted: '#d97706',
    center: { lat: 19.076, lng: 72.8777 },
    featuredLocalitySlugs: [],
    localities: [],
  },
  {
    slug: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    country: 'IN',
    status: 'coming_soon',
    tagline: 'Koramangala to Whitefield — broker reels, structured',
    accent: '#10b981',
    accentMuted: '#059669',
    center: { lat: 12.9716, lng: 77.5946 },
    featuredLocalitySlugs: [],
    localities: [],
  },
  {
    slug: 'pune',
    name: 'Pune',
    state: 'Maharashtra',
    country: 'IN',
    status: 'coming_soon',
    tagline: 'Hinjewadi to Kothrud — find flats without the scroll',
    accent: '#8b5cf6',
    accentMuted: '#7c3aed',
    center: { lat: 18.5204, lng: 73.8567 },
    featuredLocalitySlugs: [],
    localities: [],
  },
  {
    slug: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    country: 'IN',
    status: 'coming_soon',
    tagline: 'Gachibowli to Madhapur — video-proof rentals',
    accent: '#ec4899',
    accentMuted: '#db2777',
    center: { lat: 17.385, lng: 78.4867 },
    featuredLocalitySlugs: [],
    localities: [],
  },
  {
    slug: 'delhi-ncr',
    name: 'Delhi NCR',
    state: 'Delhi',
    country: 'IN',
    status: 'coming_soon',
    tagline: 'Gurgaon · Noida · South Delhi — one search layer',
    accent: '#ef4444',
    accentMuted: '#dc2626',
    center: { lat: 28.6139, lng: 77.209 },
    featuredLocalitySlugs: [],
    localities: [],
  },
  {
    slug: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    country: 'IN',
    status: 'coming_soon',
    tagline: 'Pink City rentals from real walkthrough reels',
    accent: '#f97316',
    accentMuted: '#ea580c',
    center: { lat: 26.9124, lng: 75.7873 },
    featuredLocalitySlugs: [],
    localities: [],
  },
  {
    slug: 'lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    country: 'IN',
    status: 'coming_soon',
    tagline: 'Gomti Nagar to Hazratganj — launching soon',
    accent: '#06b6d4',
    accentMuted: '#0891b2',
    center: { lat: 26.8467, lng: 80.9462 },
    featuredLocalitySlugs: [],
    localities: [],
  },
]

export const CITIES_BY_SLUG = Object.fromEntries(CITY_REGISTRY.map((c) => [c.slug, c]))